name: ci
on:
  push:
    branches:
      - master
      - main
  workflow_run:
    workflows: ["automerge"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
